/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ArmiesLazyImport = createFileRoute('/armies')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const ArmiesCreateLazyImport = createFileRoute('/armies/create')()
const ArmiesUpdateIdLazyImport = createFileRoute('/armies/update/$id')()
const ArmiesDeleteIdLazyImport = createFileRoute('/armies/delete/$id')()

// Create/Update Routes

const ArmiesLazyRoute = ArmiesLazyImport.update({
  id: '/armies',
  path: '/armies',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/armies.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ArmiesCreateLazyRoute = ArmiesCreateLazyImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ArmiesLazyRoute,
} as any).lazy(() => import('./routes/armies.create.lazy').then((d) => d.Route))

const ArmiesUpdateIdLazyRoute = ArmiesUpdateIdLazyImport.update({
  id: '/update/$id',
  path: '/update/$id',
  getParentRoute: () => ArmiesLazyRoute,
} as any).lazy(() =>
  import('./routes/armies.update.$id.lazy').then((d) => d.Route),
)

const ArmiesDeleteIdLazyRoute = ArmiesDeleteIdLazyImport.update({
  id: '/delete/$id',
  path: '/delete/$id',
  getParentRoute: () => ArmiesLazyRoute,
} as any).lazy(() =>
  import('./routes/armies.delete.$id.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/armies': {
      id: '/armies'
      path: '/armies'
      fullPath: '/armies'
      preLoaderRoute: typeof ArmiesLazyImport
      parentRoute: typeof rootRoute
    }
    '/armies/create': {
      id: '/armies/create'
      path: '/create'
      fullPath: '/armies/create'
      preLoaderRoute: typeof ArmiesCreateLazyImport
      parentRoute: typeof ArmiesLazyImport
    }
    '/armies/delete/$id': {
      id: '/armies/delete/$id'
      path: '/delete/$id'
      fullPath: '/armies/delete/$id'
      preLoaderRoute: typeof ArmiesDeleteIdLazyImport
      parentRoute: typeof ArmiesLazyImport
    }
    '/armies/update/$id': {
      id: '/armies/update/$id'
      path: '/update/$id'
      fullPath: '/armies/update/$id'
      preLoaderRoute: typeof ArmiesUpdateIdLazyImport
      parentRoute: typeof ArmiesLazyImport
    }
  }
}

// Create and export the route tree

interface ArmiesLazyRouteChildren {
  ArmiesCreateLazyRoute: typeof ArmiesCreateLazyRoute
  ArmiesDeleteIdLazyRoute: typeof ArmiesDeleteIdLazyRoute
  ArmiesUpdateIdLazyRoute: typeof ArmiesUpdateIdLazyRoute
}

const ArmiesLazyRouteChildren: ArmiesLazyRouteChildren = {
  ArmiesCreateLazyRoute: ArmiesCreateLazyRoute,
  ArmiesDeleteIdLazyRoute: ArmiesDeleteIdLazyRoute,
  ArmiesUpdateIdLazyRoute: ArmiesUpdateIdLazyRoute,
}

const ArmiesLazyRouteWithChildren = ArmiesLazyRoute._addFileChildren(
  ArmiesLazyRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/armies': typeof ArmiesLazyRouteWithChildren
  '/armies/create': typeof ArmiesCreateLazyRoute
  '/armies/delete/$id': typeof ArmiesDeleteIdLazyRoute
  '/armies/update/$id': typeof ArmiesUpdateIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/armies': typeof ArmiesLazyRouteWithChildren
  '/armies/create': typeof ArmiesCreateLazyRoute
  '/armies/delete/$id': typeof ArmiesDeleteIdLazyRoute
  '/armies/update/$id': typeof ArmiesUpdateIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/armies': typeof ArmiesLazyRouteWithChildren
  '/armies/create': typeof ArmiesCreateLazyRoute
  '/armies/delete/$id': typeof ArmiesDeleteIdLazyRoute
  '/armies/update/$id': typeof ArmiesUpdateIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/armies'
    | '/armies/create'
    | '/armies/delete/$id'
    | '/armies/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/armies'
    | '/armies/create'
    | '/armies/delete/$id'
    | '/armies/update/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/armies'
    | '/armies/create'
    | '/armies/delete/$id'
    | '/armies/update/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  ArmiesLazyRoute: typeof ArmiesLazyRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  ArmiesLazyRoute: ArmiesLazyRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/armies"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/armies": {
      "filePath": "armies.lazy.tsx",
      "children": [
        "/armies/create",
        "/armies/delete/$id",
        "/armies/update/$id"
      ]
    },
    "/armies/create": {
      "filePath": "armies.create.lazy.tsx",
      "parent": "/armies"
    },
    "/armies/delete/$id": {
      "filePath": "armies.delete.$id.lazy.tsx",
      "parent": "/armies"
    },
    "/armies/update/$id": {
      "filePath": "armies.update.$id.lazy.tsx",
      "parent": "/armies"
    }
  }
}
ROUTE_MANIFEST_END */
